### ISSUE TITLE
celi target output

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#49]
How is celi target output being generated? Can we have a default tool call to save the current section/doc/whatever iteration to json?

**Comment by x3n0cr4735** [comment]
For example, look at the save_draft tool in AP_English_Language

**Comment by DaveDeCaprio** [comment]
It would help if I understand what's not working about the current setup for you to make sure if we change something, it accomplishes what we want.

**Comment by x3n0cr4735** [comment]
Let's say for example I draft on task 5 but there are tasks 6 and 7. How will I ensure that task 5's output is being saved to target? One of the things that I have noticed for example, is emergent behavior that if I draft and then in a later task ask for a review, that the earlier task with the draft will be better. And I may not necessarily want a redraft after the review. And this is not really a hypothetical, I'm actually doing this in a fork. But I'm manually saving the output from the earlier task.

**Comment by x3n0cr4735** [comment]
What I propose is to have a standard or default "save draft" tool call that will route the output.

**Comment by DaveDeCaprio** [comment]
Ah, got it.  So it's something like:
- task 5 writes a draft and saves it
- task 6 attempts to rewrite to improve it
- task 7 reviews the rewrite versus the original and decides which one to keep.  It if likes task 6's output, it saves it.  If task 5's is good, then it does nothing.

It makes sense to do it this way because it's more robust than task 7 having to reoutput the full version of the draft that it likes.    I get it.

This makes sense, and has the advantage that it makes it easier to generalize outside of document writing tasks.  Right now, we assume the output of each task loop is text in a json file, but making it a tool allows you to have any output you want.

I'll put this in it's own PR in the next day or so.

**Comment by x3n0cr4735** [comment]
Yes, exactly 💯

**Comment by DaveDeCaprio** [comment]
Done.  I'll do a release once I get the HumanEval in later tonight.

**Comment by DaveDeCaprio** [comment]
Fixed with #56
